BEGIN;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS "user" (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "name" VARCHAR(100) NOT NULL,
    surname VARCHAR(100) NOT NULL,
    nationality CHAR(2),
    patronymic VARCHAR(100),
    sex VARCHAR(10) CHECK (sex IN ('MALE', 'FEMALE')),
    age INTEGER CHECK (age > 0 AND age < 120)
);

COMMIT;